# Generated by Django 2.2.4 on 2020-05-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, default='1901-01-01'),
        ),
    ]
