# Generated by Django 2.2.4 on 2020-05-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.CharField(default='no value', max_length=255),
            preserve_default=False,
        ),
    ]
